name: Ejecutar Script Node.js

on:
  schedule:
    - cron: '0 9 * * 1-6'  # Programar para ejecutar de lunes a sábado a las 9:00 am

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Ajusta la versión de Node.js según tus necesidades

      - name: Install Dependencies
        run: npm install  # Asegúrate de tener un package.json con las dependencias necesarias

      - name: Run Script
        run: node app.js  # Ajusta el nombre del script si es diferente
